service: python-service

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: python3.7

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: time
          method: get

plugins:
  - serverless-openwhisk
