service: env-variables-encrypted-in-a-file

frameworkVersion: "3"

plugins:
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  resetPassword:
    handler: handler.resetPassword
    environment:
      SESSION_KEY: ${self:custom.secrets.SESSION_KEY}
      EMAIL_SERVICE_API_KEY: ${self:custom.secrets.EMAIL_SERVICE_API_KEY}
