service: websocket-authorizer-example

frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect # authorizers are only for connect routes
          authorizer:
            name: auth
            identitySource:
              - 'route.request.header.Auth'
  default:
    handler: handler.default
    events:
      - websocket:
          route: $default

  auth:
    handler: handler.auth
