service: scheduled-weather-example
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    RECIPIENT: tom@carrotcreative.com
    DARK_SKY_API_KEY: abc123
    POSTMARK_API_KEY: abc123
    POSTMARK_SENDER: devops@carrotcreative.com
    LATITUDE: 40.702637
    LONGITUDE: -73.989406

functions:
  weather:
    handler: handler.run
    memorySize: 128
    timeout: 5
    events:
        # 10am UTC, daily
      - schedule: cron(0 10 * * ? *)
