service: rekognition-analysis-s3-image

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "rekognition:*"
          Resource: "*"   

functions:
  imageAnalysis:
    handler: handler.imageAnalysis
    events:
      - http:
          path: analysis
          method: post    
