service: python_service

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: python3.7

functions:
  cron:
    handler: handler.run
    events:
      - schedule: cron(* * * * *)

# remember to run npm install to download the provider plugin.        
plugins:
    - serverless-openwhisk
