service: aws-lambda-and-heroku-postgres # NOTE: update this with your service name

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
      - http: POST onrelease