service: aws-node-telegram-echo-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post
