service: function-compiled-with-babel

frameworkVersion: "3"

custom:
  babelPresets:
    - latest

plugins:
  - serverless-babel-plugin

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
