service: ruby-simple-http-endpoint

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: ruby2.7
  project: l<projectname>
  credentials: ~/.config/gcloud/creds.json # path must be absolute

functions:
  simpleGet:
    handler: hello
    events:
      - http: path
